app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /default/

frontoffice:
    resource: "@FrontofficeBundle/Controller/"
    type:     annotation
    prefix:   /

backoffice:
    resource: "@BackofficeBundle/Controller/"
    type:     annotation
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"